# Generated by Django 4.2.7 on 2026-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('total_ejecutado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('componente_pam', models.CharField(blank=True, max_length=150, null=True)),
                ('actor_dirigido', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_beneficiarios', models.IntegerField(blank=True, null=True)),
                ('entrega_dotacion', models.BooleanField(blank=True, null=True)),
                ('descripcion_dotacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvanceActividad',
            fields=[
                ('id_avance', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_corte', models.DateField()),
                ('porcentaje', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'avance_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=250)),
                ('codigo_bpin', models.CharField(blank=True, max_length=30, null=True)),
                ('codigo_pi', models.CharField(blank=True, max_length=30, null=True)),
                ('apropiacion_definitiva', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('adicion', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('recursos', models.CharField(blank=True, max_length=80, null=True)),
                ('avance_cargue_pct', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANEADO', 'PLANEADO'), ('EN_EJECUCION', 'EN_EJECUCION'), ('FINALIZADO', 'FINALIZADO'), ('SUSPENDIDO', 'SUSPENDIDO')], max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoMeta',
            fields=[
                ('id_proyecto_meta', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_planeado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_logrado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('observacion', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'db_table': 'proyecto_meta',
                'managed': False,
            },
        ),
    ]
