# Generated by Django 4.2.7 on 2026-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorGestion',
            fields=[
                ('id_indicador', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('definicion', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('periodicidad', models.CharField(choices=[('MENSUAL', 'MENSUAL'), ('TRIMESTRAL', 'TRIMESTRAL'), ('SEMESTRAL', 'SEMESTRAL'), ('ANUAL', 'ANUAL')], max_length=12)),
                ('fuente', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'indicador_gestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadorGestionValor',
            fields=[
                ('id_valor', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_corte', models.DateField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observacion', models.CharField(blank=True, max_length=600, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'indicador_gestion_valor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id_meta', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'meta',
                'managed': False,
            },
        ),
    ]
