# Generated by Django 4.2.7 on 2026-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id_ie', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_dane', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=250)),
                ('id_municipio', models.IntegerField()),
            ],
            options={
                'db_table': 'institucion_educativa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LineaEstrategica',
            fields=[
                ('id_linea', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'linea_estrategica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LineaVigencia',
            fields=[
                ('id_linea_vigencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_linea', models.BigIntegerField()),
                ('id_vigencia', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'linea_vigencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('rol', models.CharField(max_length=30)),
                ('activo', models.BooleanField()),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vigencia',
            fields=[
                ('id_vigencia', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(unique=True)),
                ('estado', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vigencia',
                'managed': True,
            },
        ),
    ]
